### ISSUE TITLE
Downloading of exports through client

### ISSUE THREAD

**Issue by marten** [zooniverse/panoptes-python-client#1]
People at .Astro want a way to automatically request and fetch classification/aggregation exports.

**Comment by calders** [comment]
I see this is now implemented in the project.py file. Excellent! :+1: 

However, when I try to run the following code:
> filename = "panoptes_test2_export.csv"
> from panoptes_client import SubjectSet, Subject, Project, Panoptes
> Panoptes.connect(username=username, password=password)
> project = Project.find(slug='zooniverse/radio-meteor-zoo')
> r = project.get_classifications_export(generate=True, wait=True, wait_timeout=1800)

I get the following error after a while:

>   File "C:/Users/stijnc/Desktop/dotAstronomy/zooniverse/panoptes_test2.py", line 17, in <module>
>     r = project.get_classifications_export(generate=True, wait=True, wait_timeout=1800)
> 
>   File "C:\Anaconda\lib\site-packages\panoptes_client\project.py", line 37, in get_classifications_export
>     export = self.wait_classifications_export(wait_timeout)
> 
>   File "C:\Anaconda\lib\site-packages\panoptes_client\project.py", line 54, in wait_classifications_export
>     export_metadata = export_description['media'][0]['metadata']
> 
> TypeError: 'NoneType' object has no attribute '__getitem__'

What is going wrong?

**Comment by astopy** [comment]
@calders I think the client is getting an empty response from the API. I've managed to reproduce the same problem here, but it doesn't seem to happen every time. I'm still looking into it.

**Comment by astopy** [comment]
@calders this should be fixed by #23, which will be included in v0.3.

**Comment by astopy** [comment]
I'm going to open separate issues for other types of export.
