### ISSUE TITLE
Retrieving classifications with last_id parameter

### ISSUE THREAD

**Issue by roelofsaj** [zooniverse/panoptes-python-client#104]
I'm trying to set up a routine for downloading and processing our classification data without requesting the csv file exports. I was hoping to process through the classifications with something like this:
<pre><code>for c in Classification.where(scope='project', project_id=2834, workflow_id=2119, last_id=13571600):
    print(c.id)  //this is just for testing... actual processing goes here!
</code></pre>

When I started testing this, the lists of IDs looked suspiciously short, so I started checking with this:
<pre><code>c = [c.id for c in Classification.where(scope='project', project_id=2834, workflow_id=2119, last_id=13571600)];
//This should be 277 classifications
print(len(c))
//...but it's only 28
</code></pre>

If I call this with a last_id where I'd expect to get 27 or fewer classifications, it works. However, if I call it with an lower last_id, where I'd expect to get more than 27 classifications, only 27 or 28 are returned. If I omit the <code>last_id</code> parameter, I get all of the expected 486 classifications for this workflow. 

This seems like a bug, unless I'm doing something entirely wrong here? If that's the case, it'd be great to know the correct way to do this classification retrieval.

Thanks!
-Abbey

**Comment by camallen** [comment]
This is a bug with the API, I've just created an issue for it, https://github.com/zooniverse/Panoptes/issues/2334

Leave this open for now but feel free to add comments to the panoptes api issues. Thanks for reporting @roelofsaj 👍

**Comment by jschell42** [comment]
Hi, any updates on this? Thanks!

**Comment by camallen** [comment]
Nope - follow the API issue linked above for more deatils. Once that is fixed the client should work as is without any changes.

**Comment by jschell42** [comment]
Great, thanks for the update!

Justin

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

Justin Schell
Director, Shapiro Design Lab
University of Michigan Libraries
PhD, Comparative Studies in Discourse and Society
University of Minnesota
@612to651
Pronouns: He, Him, His

**Comment by astopy** [comment]
I'm going to close this here for now, since this is being tracked in zooniverse/Panoptes#2334
