### ISSUE TITLE
check local file size is reasonable before creating a subject / uploading to s3

### ISSUE THREAD

**Issue by camallen** [zooniverse/panoptes-python-client#121]
Some project images we are hosting are ~1/2MB and are very large dims (3264 x 2448), e.g  https://www.zooniverse.org/projects/sbradford/western-montana-wildlife/classify 

Perhaps before creating a subject when parsing a manifest we could do a quick check on large images and error / warn if so?

**Comment by astopy** [comment]
This is probably more suited to being in the CLI. I've created an issue there to track it.
