### ISSUE TITLE
Support multiple file URLs for a single subject location

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/panoptes-python-client#125]
The audio file viewer in PFE expects subjects with locations in the form
`subject.locations = [{'image/jpeg': image_URL, 'audio/mpeg': audio_URL}]`
ie. a single subject location (frame in PFE) that has an image and an audio file.

Is it possible to upload multiple files to a single subject location via the python CLI? If not, is this a feature that could be added?

**Comment by eatyourgreens** [comment]
Looking through the subject code, could `subject.add_locations` be modified to take multiple local files as an array? `subject.add_location(['/local/image/file.jpg', '/local/audio/file.mp3'])`

**Comment by astopy** [comment]
Yeah, that should be simple enough to implement.

**Comment by li-yp** [comment]
@astopy After updating the panoptes client using the command 
pip2 install -U panoptes-client,
I ran into an error when executing the following code:

project = Project.find(id=4846)
subjectSet = SubjectSet()
subjectSet.links.project = project

subjectSet = SubjectSet()
subjectSet.links.project = project
subjectSet.display_name = 'Testing Combined Uploads'
print subjectSet
subjectSet.save()
subjects = []
#for subjectPath in subjectPaths:
subjects.append(Subject())
subjects[-1].links.project = project
subjects[-1].add_location(['/home/mp3/Class3_1.mp3','/home/pic/Class3_1.png'])
subjects[-1].save()
subjectSet.add(subjects)
print('Done')


The error message is:

Traceback (most recent call last):
  File "zoo.py", line 35, in <module>
    subjects[-1].add_location(['/home/mp3/Class3_1.mp3','/home//pic/Class3_1.png'])
  File "/home/yp/.local/lib/python2.7/site-packages/panoptes_client/subject.py", line 104, in add_location
    f.close()
AttributeError: 'list' object has no attribute 'close'


Could you please check if this is a problem with my update or the code?

Thanks!

**Comment by astopy** [comment]
@li-yp This won't work until version 1.1 of the client is released. The current version of the client doesn't support multiple files per location.

**Comment by li-yp** [comment]
@astopy Got it. Can I ask when version 1.1 is planned be released? Previously, there seems to be an issue that Panoptes is rejecting mp3 files. Has that been fixed? Right now, I am using Firefox to upload mp3s, as suggested in https://github.com/zooniverse/Panoptes/issues/2458

Before that, how can I upload multiple files per location? The problems that I encounter is that if I want to upload 100 pairs of audio+spectrogram, I have to first upload 100 audios using Firefox (previous tries using Chrome or PFE both failed). Then I have to upload the 100 spectrograms and associated them with each audio using code like 
subjects[-1].add_location('/home/pic/Class1_58.png')
subjects[-1].add_location({'audio/mp3':'https://panoptes-uploads.zooniverse.org/production/subject_location/5f19cb68-6718-40b4-acfa-842b96ce7d5a.mpga'})

But I am not sure whether I can retreive the subject locations of correctly matched audio files using code like:

subject_set=SubjectSet.find(14913)
for subject in subject_set.subjects:
    print("%s," % (subject.locations))

That is, I am not sure whether the order of subjects returned from the code above, hence it is difficult to associate the image and spectrogram.

**Comment by eatyourgreens** [comment]
Turns out Panoptes will throw out all but the first file location if you try to post multiple MIME types to a single location, so we're going to close this and look alternative ways to configure subject rendering for workflows or subject sets. Default behaviour would be to treat every subject as a slideshow, but you could override that for audio or video workflows.

**Comment by eatyourgreens** [comment]
Forgot to add: fixing this in Panoptes would be a breaking change for the existing API.

**Comment by li-yp** [comment]
@eatyourgreens I think that using the manifest with multiple MIMIE types works now, at least in my trial with Firefox.

And code like the following lines will post multiple MIME types to a single location in a new subject set.
subject.add_location({'audio/mpeg': audio_url})
subject.add_location({'image/png': 'image_url'})

**Comment by eatyourgreens** [comment]
@li-yp it turns out my understanding of the Panoptes API was wrong. Glad to hear it is all working now.
