### ISSUE TITLE
Client returns error after successful subject_set.add(1234)

### ISSUE THREAD

**Issue by PmasonFF** [zooniverse/panoptes-python-client#144]
The following code **successfully** links all sub in add_subjects but log file reports link failed for most but not all cases - ie something is triggering the error:
````
    k = 0
    for sub in add_subjects:
        try:
            k += 1
            subject_set.add(sub)
            log_file(str(datetime.now())[0:19] + '  ' + str(sub) + ' linked')
        except:
            log_file(str(datetime.now())[0:19] + '  ' + str(sub) + ' link failed')

    log_file(str(datetime.now())[0:19] + '  ' + str(k) + ' subjects successfully linked.')
````
All subjects show as linked in the project builder and the next days subject export.

Also **Very minor** typo in help file for panoptes_client.classification module:
 my_classifications = Classifiction.where()

**Comment by PmasonFF** [comment]
PS I know that all the subjects in add_subjects ( which is a set) can be added in one go but the error checking was to verify each subject linked....

**Comment by astopy** [comment]
Thanks. Could you remove the try/except and let me know what the exception is?

**Comment by PmasonFF** [comment]
Will do including removing the log_file step on the next run.  I could not recreate the error today linking the subjects to a subject set in a different project....

**Comment by PmasonFF** [comment]
Removed the try except statements. The log_file function was modified - linked 4898 subjects with no errors!
With this situation it appears the error likely came from the function rather than the subject-set.add(sub).
I think it best to close out this issue.
