### ISSUE TITLE
400 Bad Response when uploading metadata with inconsistent types or nan values

### ISSUE THREAD

**Issue by RustyPanda** [zooniverse/panoptes-python-client#150]
When adding manifest items to a subject set, the client fails if (I think) the data types in the manifest metadata are not consistent with previous manifest items, OR are np.nan.

Context:
Adding new galaxy to a subject set on Galaxy Zoo (Panoptes).  Unlike previous galaxies, this galaxy has a metadata entry where one value is of type np.nan rather than float.

Error:
The response object from requests.session() throws a JSONDecodeError at the first character. Printing the response object shows it's a 400 Bad Request. 

Resolution:
Converting np.nan values to float flags (e.g. -999) allows the upload to succeed.

I think that either the server cannot accept nan values, or the types must be consistent with previous manifest entries. This was easy to fix once tracked down, but was not obvious from the error thrown. Would it be possible to have the server send a descriptive response that triggers an explanatory exception?

**Comment by astopy** [comment]
Could you run that with `PANOPTES_DEBUG=true` in the environment and copy/paste the full output with the backtrace? I'd like to see exactly what it's submitting to the API.

**Comment by CKrawczyk** [comment]
Numpy values (`np.int`, `np.flaot32`, etc...) can't be transformed into json by default, but you can write a custom encoder to cast them into usable types, see https://github.com/zooniverse/aggregation-for-caesar/blob/master/routes.py#L10-L19 for an example I used for the aggregation code.

**Comment by RustyPanda** [comment]
Some time later - just to confirm that this is definitely due to the payload having values that are not supported by json - in my case, np.nan and masked array values.
