### ISSUE TITLE
Retrieve project or subject_set id

### ISSUE THREAD

**Issue by macrocosme** [zooniverse/panoptes-python-client#155]
Is it currently possible to retrieve my own `project`'s `id` from a python script? For example, I can load a `project` if I go the zooniverse website, and look at the project ID that appears on the page. However, I am unsure how to retrieve this ID from the code (e.g. at project creation). 

Thanks in advance

**Comment by astopy** [comment]
Yup, you can do that! You can access `Project.id` after saving the project:

```python
>>> p = Project()
>>> p.display_name = 'test project creation'
>>> p.private = True
>>> p.primary_language = 'en'
>>> p.description = 'test'
>>> p.save()
>>> print(p.id)
```

Or you can query for projects owned by a specific user (so in this case you would use your own login name):

```python
>>> for project in Project.where(owner='username'):
...    print(project.id)
```
