### ISSUE TITLE
Can not update metadata in version 1.0.1

### ISSUE THREAD

**Issue by PmasonFF** [zooniverse/panoptes-python-client#165]
This simple code which modified metadata for an existing subject worked fine under 1.0, but no longer works under version 1.0.1:

```
subject = Subject(24195132)
print(subject.id, subject.metadata)
new_meta = {'file': 'Chalcedony1a.jpg', 'image_number': 'F201508250852636a'}
subject.metadata.update(new_meta)
subject.save()
print(subject.id, subject.metadata)`
```

The error message Is as follows:
24195132 {'file': 'Chalcedony1.jpg', 'image_number': 'F201508250852636'}
Traceback (most recent call last):
  File "C:/py/Data_digging/Panoptes_client/work_with_Client_examples.py", line 23, in <module>
    subject.save()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\panoptes_client\subject.py", line 55, in save
    response['subjects'][0]['locations'],
TypeError: 'NoneType' object is not subscriptable

subject.save() still works fine for new subjects where subject.add_locations() is defined, though it is not possible to add a additional location to an existing subject with version 1.0.1 while this still is possible with the previous version.
Attention: @adammcmaster

**Comment by PmasonFF** [comment]
@adammcmaster

**Comment by PmasonFF** [comment]
I have tried to reinstall Python 3.6.6, and panoptes_client 1.01, ie make sure it is not some issue in my environment.  I also installed the development version from the Git - neither worked with this code, reinstalled 1.0 with Python 3.6.6 and it works fine.  Anything else I can try?

**Comment by adammcmaster** [comment]
This bug was introduced by #159, because of this line: https://github.com/zooniverse/panoptes-python-client/commit/c592b07745761e724763f0037e3bda3e341e4033#diff-5a2fd2b9b07f19054a007f16d0f688a5R672

**Comment by adammcmaster** [comment]
Modifying the metadata dictionary doesn't record anything in `modified_attributes`, so no update request is made.

There's also a second bug, in that `Subject.save()` will fail if you call it when nothing has changed.

**Comment by adammcmaster** [comment]
@PmasonFF Version 1.0.2 is out now with the fix for this. Thanks for reporting!
