### ISSUE TITLE
'Generate' option in Project export raises project id not found error

### ISSUE THREAD

**Issue by facepalm** [zooniverse/panoptes-python-client#171]
I'm trying to pull current classification data from the Galaxy Zoo project

`export = Project(5733).get_export('classifications')`
raises an exception
`panoptes_client.panoptes.PanoptesAPIException: No classifications_export exists for project #5733`

Which is fine - the documentation suggests a generate flag:

`export = Project(5733).get_export('classifications', generate = True)`

But this no longer finds the project
`panoptes_client.panoptes.PanoptesAPIException: Could not find project with id='5733'`

**Comment by PmasonFF** [comment]
This error is consistent with you not having connected to Panoptes with credentials that allow you to generate an export for this project.  The client (version 1.0.2 is working correctly for me using this line of code when I am connected correctly to a project for which I have status to generate exports, and gives the message as you received if I attempt to generate an export for a project when connected with credentials which do not give me export generation ability for that project.

**Comment by facepalm** [comment]
Makes sense.  Could use a more informative error message, then.

**Comment by facepalm** [comment]
Which I interpreted as "the classification hasn't been exported recently enough, --generate a new one"

At any rate, is there some other way to access classification data (ideally, consensus ratings) without having edit credentials? I don't want to edit anything, I just want to pair subjects with existing classifications to try training an automated classifier to do the rest.

**Comment by PmasonFF** [comment]
As far as I know you need collaborator status to generate exports, but only the url link to previously generated exports to download them so contact the project owner to see if they will give you the link to the latest export. What you get will be the raw export not flattened or aggregated in any way - which is a whole other kettle of fish - see [here](https://github.com/zooniverse/Data-digging/tree/master/example_scripts)

**Comment by facepalm** [comment]
That's just fine.  I'll take a complicated csv over a javascript interface any day.

I think I'll go ahead and close this.  Thanks for your help!
