### ISSUE TITLE
Non-image subject uploads shouldn't return API errors

### ISSUE THREAD

**Issue by zwolf** [zooniverse/panoptes-python-client#185]
A few issues have been opened recently on the CLI (https://github.com/zooniverse/panoptes-cli/issues/81, https://github.com/zooniverse/panoptes-cli/issues/84) that are due to the API rejecting the detected mimetype (`image/None`) that results from a missing `libmagic` install. The error that the user of the CLI sees is not useful to them (`Validation failed: Locations is invalid`). 

Instead, these misdetections should themselves be detected by the client and its own error should be produced. They should not be sent to the API.

Checking for `libmagic` and installing it if it's missing is the answer here, but that can be confusing as well. Calling `panoptes info` can be misleading if there are multiple python versions installed and the one that the CLI uses by default (say, the system version) isn't what the client will use (a brew installed version). I'm not sure how this might happen since the client calls are wrapped by the CLI, but that seems to be the case in issue 84 up there.

**Comment by adammcmaster** [comment]
The above PR will raise a more helpful error instead of submitting it to the API.

I would guess the issue in #84 was that the python-magic module was installed, but the `libmagic` shared library wasn't. The client will log a warning message in that case now.
