### ISSUE TITLE
Cannot create and save new subject set since 1.1

### ISSUE THREAD

**Issue by miclaraia** [zooniverse/panoptes-python-client#205]
This [script](https://github.com/miclaraia/muon_analysis/blob/master/muon/scripts/test_panoptes_connection.py) illustrates the problem. The script fails on `subject_set.save()`. Mimics the instructions in the tutorial detailed in the [docs](https://panoptes-python-client.readthedocs.io/en/v1.1/user_guide.html#tutorial-creating-a-new-project).

Tries to get a project, create a subject set, link the subject set to the project, then save the subject set. The following trace is shown on `subject_set.save()`:
```
  File "test_panoptes_connection.py", line 23, in main
    subject_set.save()
  File ".../venv/lib/python3.6/site-packages/panoptes_client/panoptes.py", line 815, in save
    etag=self.etag
  File ".../venv/lib/python3.6/site-packages/panoptes_client/panoptes.py", line 404, in post
    retry=retry,
  File ".../venv/lib/python3.6/site-packages/panoptes_client/panoptes.py", line 281, in json_request
    json_response['errors']
panoptes_client.panoptes.PanoptesAPIException: {"schema"=>"did not contain a required property of 'links'"}
```

**Comment by camallen** [comment]
I assume the link payloads are incorrect. Can you get a trace of the data / payloads sent to the API and report back with hopefully relevant example data? 

Use the env var to turn it on https://github.com/zooniverse/panoptes-python-client/blob/master/CHANGELOG.md#10-2017-11-03
```
export PANOPTES_DEBUG=true
```

In the meantime downgrading the client version to last release will fix it.

**Comment by marco-willi** [comment]
This is a simple example with DEBUG mode on.

```
my_project = Project('7978')
new_set = SubjectSet()
new_set.links.project = my_project
new_set.display_name = 'test'
new_set.save()
DEBUG:urllib3.connectionpool:https://www.zooniverse.org:443 "POST /oauth/token HTTP/1.1" 200 1003
DEBUG:panoptes_client:json={'subject_sets': {'display_name': 'test'}}
DEBUG:redo:attempt 1/1
DEBUG:urllib3.connectionpool:https://www.zooniverse.org:443 "POST /api/subject_sets HTTP/1.1" 422 96
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/packerc/will5448/.local/lib/python3.6/site-packages/panoptes_client/panoptes.py", line 815, in save
    etag=self.etag
  File "/home/packerc/will5448/.local/lib/python3.6/site-packages/panoptes_client/panoptes.py", line 404, in post
    retry=retry,
  File "/home/packerc/will5448/.local/lib/python3.6/site-packages/panoptes_client/panoptes.py", line 281, in json_request
    json_response['errors']
panoptes_client.panoptes.PanoptesAPIException: {"schema"=>"did not contain a required property of 'links'"}
```

**Comment by camallen** [comment]
Thanks @marco-willi 
> panoptes_client.panoptes.PanoptesAPIException: {"schema"=>"did not contain a required property of 'links'"}

That certainly looks like the payload is incorrectly formatted, especially with the explicit link setup `new_set.links.project = my_project`

**Comment by adammcmaster** [comment]
Thanks for reporting this! I'll be releasing an update with the fix next week.
