### ISSUE TITLE
Stop old versions failing silently on subject uploads

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/panoptes-python-client#254]
I suggest adding a user agent header to [the defaults](https://github.com/zooniverse/panoptes-python-client/blob/master/panoptes_client/panoptes.py#L56) including the client version number, and then have the API reject subject creation requests from old versions.

**Comment by camallen** [comment]
👍  Having a client version in the request to reflect upon will useful for future possible breaking changes that the API could use to either reject requests or signal to the client that they need to take action.

**Comment by adammcmaster** [comment]
Would it make sense to add a header with some kind of API version number (or even just an updated date for the client) so that you could do that sort of thing across different clients? (Otherwise you'd end up maintaining a list of every client in Panoptes.)

**Comment by camallen** [comment]
The client already supplies an API version number header via https://github.com/zooniverse/panoptes-python-client/blob/7dc7318d79065216c8857a1d142f771b81d461b3/panoptes_client/panoptes.py#L56

Perhaps a `User-Agent` header that outlines the requesting client name and version (OS as well)? https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

**Comment by adammcmaster** [comment]
Ah, I didn't realise that's what that version number was for. I think I would use that to denote what functionality the client supports (so that you can use the same logic for PFE etc). It still makes sense to add client name, version, OS, etc. as well though.

**Comment by lcjohnso** [comment]
But as we discussed on a call this morning, this sort of fix will not help the current issue of people with old versions, as they would need to update in order to start getting the warnings/errors!  But still a good idea to consider for the future.

**Comment by adammcmaster** [comment]
If the API rejects the requests that would raise an error in the old client versions, so people wouldn't need to update for that. The downside is that people will get errors even on version 1.3.0 as you'll need to do a new release to bump the API version number.

**Comment by adammcmaster** [comment]
So to be clear, that would stop the current issue.
