### ISSUE TITLE
Downloading aggregation exports

### ISSUE THREAD

**Issue by astopy** [zooniverse/panoptes-python-client#26]

**Comment by tgirgin23** [comment]
Is there an easy way to get the aggregation export using something similar to this?

`agg = project.get_export("aggregation",generate=True, wait=True, wait_timeout=30)
`
This line works if the first argument is "workflows" or "classification", however I can't make it work with "aggregation".

Thank you

**Comment by astopy** [comment]
@tgirgin23 I believe it should work with "aggregations" -- note the 's' on the end. Let me know if that doesn't work though.

**Comment by tgirgin23** [comment]
@astopy Seems like "aggregations" is working. However, we are only getting a README file within the gzip. Is this maybe due to aggregations being an experiment? 

Thanks

**Comment by astopy** [comment]
@tgirgin23 It could be that something is going wrong when it generates the files. Could you let me know the ID of your project and I'll take a look?
