### ISSUE TITLE
panoptes_client-1.4.0 access token errror 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/panoptes-python-client#265]
I'm trying to use a jupyter notebook previous to upload subjects to my project and I'm getting 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-82e4c76da0de> in <module>
----> 1 project = Project.find("11435")

~/opt/anaconda3/envs/zooniverse/lib/python3.8/site-packages/panoptes_client/project.py in find(cls, id, slug)
     80             return None
     81         try:
---> 82             return cls.where(id=id, slug=slug).next()
     83         except StopIteration:
     84             raise PanoptesAPIException(

~/opt/anaconda3/envs/zooniverse/lib/python3.8/site-packages/panoptes_client/panoptes.py in where(cls, **kwargs)
    672 
    673         _id = kwargs.pop('id', '')
--> 674         return cls.paginated_results(*cls.http_get(_id, params=kwargs))
    675 
    676     @classmethod

~/opt/anaconda3/envs/zooniverse/lib/python3.8/site-packages/panoptes_client/panoptes.py in http_get(cls, path, params, headers, retry, **kwargs)
    618     @classmethod
    619     def http_get(cls, path, params={}, headers={}, retry=True, **kwargs):
--> 620         return Panoptes.client().get(
    621             cls.url(path),
    622             params,

~/opt/anaconda3/envs/zooniverse/lib/python3.8/site-packages/panoptes_client/panoptes.py in get(self, path, params, headers, endpoint, retry)
    314         retry=False,
    315     ):
--> 316         return self.json_request(
    317             'GET',
    318             path,

~/opt/anaconda3/envs/zooniverse/lib/python3.8/site-packages/panoptes_client/panoptes.py in json_request(self, method, path, params, headers, json, etag, endpoint, retry)
    259         retry=False,
    260     ):
--> 261         response = self.http_request(
    262             method=method,
    263             path=path,

~/opt/anaconda3/envs/zooniverse/lib/python3.8/site-packages/panoptes_client/panoptes.py in http_request(self, method, path, params, headers, json, etag, endpoint, retry)
    191         headers = _headers
    192 
--> 193         token = self.get_bearer_token()
    194 
    195         if self.logged_in:

~/opt/anaconda3/envs/zooniverse/lib/python3.8/site-packages/panoptes_client/panoptes.py in get_bearer_token(self)
    557                 raise PanoptesAPIException(token_response['errors'])
    558 
--> 559             self.bearer_token = token_response['access_token']
    560             if (self.bearer_token and grant_type == 'client_credentials'):
    561                 self.logged_in = True

KeyError: 'access_token'

when I run `project = Project.find("11435")`

I'm running 

```
import numpy as np
import pandas as pd
import time
from panoptes_client import Panoptes, Project, SubjectSet, Subject

Panoptes.connect(username='mschwamb', password='my_password_here')

project = Project.find("11435")
```

@lcjohnso  I can't upload subjects to the Planet Hunters NGTS site to get you the 300 subjects for a beta test because of this.

**Comment by mschwamb** [comment]
I don't get any errors on the connect and I'm using a conda environment that only has the panoptes client package and whatever it needs installed. I'm not sure what else to do. I've tried different internet connections (work and phone) in case that's the issue.

**Comment by mschwamb** [comment]
I am limited to conda python environments by the sysadmin so that's the only way I can use python packages is to install it into a conda environment.

**Comment by mschwamb** [comment]
I'm going to completing wipe anaconda and reinstall  from there in case my entire conda install is corrupt.

**Comment by mschwamb** [comment]
I've tried a new conda install and created a new environment. No luck

**Comment by lcjohnso** [comment]
Closing now.  This behavior was found to be the result of two things:
1. The use of libraries outside the current active conda environment.  As an example: if Jupyter isn't installed in the Zooniverse-specific environment, the Jupyter kernel used at runtime might be associated with the `base` or other different environment and python package library mismatches may occur.
2. Be sure to call `Panoptes.connect()` with username and password credentials, not just instantiating the `Panoptes()` class, as the `connect()` call is necessary to establish contact with the Zooniverse API.
