### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/panoptes-python-client#309]
There are a few commits since the last release, but in particular #302 needs to be released as it is blocking a new version of `requests` that fixes security vulnerabilities.

**Comment by yuenmichelle1** [comment]
Closed with https://github.com/zooniverse/panoptes-python-client/pull/315 v1.6.2 is up in pypi. h[ttps://pypi.org/project/panoptes-client/](https://pypi.org/project/panoptes-client/)

**Comment by adammcmaster** [comment]
@yuenmichelle1 Thank you!
