### ISSUE TITLE
panoptes-client hangs on import?

### ISSUE THREAD

**Issue by Jordan-Pierce** [zooniverse/panoptes-python-client#319]
I understand that the module is connecting, but it literally just hangs on the import statement, somewhat randomly, I might add.

Version is `1.6.2`, but have downgraded to `1.6.1` and the problem still persists (though it wasn't like this before the bump to `1.6.2`). Impossible to push up new subject sets.

Tried on other computers and networks, same issue.

Thoughts?

**Comment by PmasonFF** [comment]
What is the specific error you are receiving?  Python Version?, OS?

**Comment by PmasonFF** [comment]
I shudder when my teams mention conda and windows in the same breath.  Given the nashing of teeth I have heard from various teams that have tried to use it, I recommend you avoid it and use pip to setup your environment -- though I don't think the issue you are describing has been part of the the litany of woes...

Still everything has been working for me recently (apart from the stale object issue which I have worked around by modifying how I add new subjects to subject sets AFTER they are all uploaded).

Perhaps use something like PyCharm (Edu or Community) to build an environment.  It will have better error reporting and uses pip for package installation. It seems to work better for windows than most other solutions.

As well you might add python-magic-bin as a last step to drop the libmagic warning which I think is still an issue in 1.6.2 release.

**Comment by Jordan-Pierce** [comment]
@PmasonFF I'm not using conda to install `pantopes-client`, I'm using it to create a virtual environment; I've already read that y'all are having issues creating a conda feedstock for `pantopes-client`, thus avoiding installing it that way. 

I'll try to create a virtual environment using `venv` and install `panoptes-client` using pip (again).

But really, if it hangs on import (on both my machine, and others with the organization) then it seems to me to imply it's a network connect issue; I'm assuming part of the import process involves connecting to your server...

**Comment by Jordan-Pierce** [comment]
Yep, computer-related issue, probably trying to connect and it's being blocked on my side.

**Comment by PmasonFF** [comment]
Well the good news is that if it is happening for you and not for anyone else, the solution is likely something you can fix.  Generally when things go wrong for me I get error messages, eg for incorrect credentials, or if zooniverse drops the connection requests will error etc.  That it is hanging may indicate that the Panoptes.connect is failing in some manner that it does not raise an error.  perhaps try a bare connect Panoptes.connect() with no user credentials and see if that will connect.
