### ISSUE TITLE
Deprecate Subject.subject_sets()

### ISSUE THREAD

**Issue by astopy** [zooniverse/panoptes-python-client#32]
I guess we can get rid of [this method](https://github.com/zooniverse/panoptes-python-client/blob/master/panoptes_client/subject.py#L78) once zooniverse/Panoptes#1899 is deployed.

**Comment by astopy** [comment]
cc @camallen Can you let me know once that's deployed?

**Comment by camallen** [comment]
@astopy that is on prod now.
