### ISSUE TITLE
Link data to an existing subject set

### ISSUE THREAD

**Issue by camallen** [zooniverse/panoptes-python-client#37]
Can i find an existing subject set to link data to? [here](https://github.com/zooniverse/panoptes-python-client/blob/67e11e16cd91689e62939a6ba54ff7769259a525/panoptes_client/subject_set.py) doesn't seem to have a find by id function..

**Comment by astopy** [comment]
Yup, it inherits it from  [`PanoptesObject`](https://github.com/zooniverse/panoptes-python-client/blob/master/panoptes_client/panoptes.py#L428)

**Comment by camallen** [comment]
thanks
