### ISSUE TITLE
New functionality for Gravity Spy 

### ISSUE THREAD

**Issue by srallen** [zooniverse/panoptes-python-client#4]
- [x] Add module for project preferences
- [x] Methods for get preferences 
- [x] Can save updated preferences
- [x] Ability to pass User and Project objects to find Project Preferences
- [x] Update subject-set link on a subject (one possible outcome of algorithm)
- [x] ~~Get classifications for a project (may not be needed if listening to kinesis stream is figured out)~~ Will use Kinesis
- [ ] Add auth module for client credentials

**Comment by srallen** [comment]
ProjectPreferences save is returning a 412.

**Comment by astopy** [comment]
@srallen That should be fixed in #11.

I think maybe we should change `user_id` and `project_id` to just `user` and `project` in `ProjectPreferences.find()` to allow passing `User` and `Project` instances (and just check the types in `find` to see if it's an ID or an instance). What do you think?

**Comment by srallen** [comment]
@astopy For Gravity Spy's purposes, they don't need to do this, but if there's a scenario you can think of where this will be useful, then that sounds good to me.

**Comment by astopy** [comment]
Yeah, I can imagine a lot of cases where someone might have a `User` object and `Project` object and it'd just be cleaner to call `ProjectPreferences.find(user, project)` rather than `ProjectPreferences.find(user.id, project.id)` every time.

**Comment by srallen** [comment]
I'm gonna close this and open specific issues for the remaining work to be done.
