### ISSUE TITLE
Make save_settings() a class method

### ISSUE THREAD

**Issue by srallen** [zooniverse/panoptes-python-client#43]
This needs to be a class method instead of an object method: https://github.com/zooniverse/panoptes-python-client/blob/master/panoptes_client/project_preferences.py#L35

**Comment by astopy** [comment]
How come this needs to be a class method?

**Comment by srallen** [comment]
@astopy Only users can fetch their own project preferences and this won't be changing (see zooniverse/Panoptes#1920). The method as written before needed an instance of `ProjectPreferences` since it was using the links to pass the project id and user id in the post and then reloading itself. Now, I can call `ProjectPreferences.save_settings()` directly, which is how it'll be used by Gravity Spy. Since my python is weak, though, I'm open to suggestion. I just needed to get this out there so I could finish the PFE UI stuff and GS could work on their algorithm.

**Comment by astopy** [comment]
Ah, I see. That makes sense.
