### ISSUE TITLE
Adding subjects to an existing subject set

### ISSUE THREAD

**Issue by calders** [zooniverse/panoptes-python-client#5]
In the example is shown how you can create a new subject set and add subjects to it. Is it also possible to add subjects to an already existing subject set? How?

**Comment by astopy** [comment]
Sure, you can use the subject set's ID to look it up like so:

```python
subject_set_id = 1234
subject_set = SubjectSet.find(subject_set_id)
```

The `.find()` method should work with every class to search by ID.
