### ISSUE TITLE
Trouble listing subjects (SubjectSet.find)

### ISSUE THREAD

**Issue by iancrossfield** [zooniverse/panoptes-python-client#76]
I cannot successfully list the subjects in my project using the example provided in the ReadMe. This is for Subject Set 8596 for project 3757:

> from panoptes_client import SubjectSet, Subject, Project, Panoptes
> 
> ss = 8596
> proj = 3757
> subjset2 = SubjectSet.find(ss)
> 
> subs = []
> for ii, sub in enumerate(subjset2.subjects()):
>     subs.append(sub)
>     print sub.links.raw['project']

The result should a large number of "3757" printed to screen.  Instead, "3757" is printed to screen 20 times, and then all subjects loaded from that point return project number "1".  Either the example or code is wrong, or my implementation... Any advice?

**Comment by camallen** [comment]
@iancrossfield this looks like a bug in the API that is returning the incorrect paging hrefs. I'll look into it.

**Comment by iancrossfield** [comment]
Thanks @camallen !  Good to hear it wasn't just me -- just let me know what you find.

**Comment by iancrossfield** [comment]
I removed and reinstalled panoptes, but still get the same behavior as in my initial issue report...

**Comment by astopy** [comment]
@iancrossfield The fix for this has been merged into our backend code, but it won't actually be deployed until some time next week (I would guess Monday).

**Comment by camallen** [comment]
@iancrossfield confirming this has been deployed, please report back if you're still having errors.
