### ISSUE TITLE
Additional Examples

### ISSUE THREAD

**Issue by brendancol** [zooniverse/panoptes-python-client#82]
Hey hey, awesome project.  Couple of questions:

Can y'all provide some of the following examples. I couldn't quite figure out how to:
- delete a project using the `Project.delete` method
- add an existing workflow to an new project?
- delete a Project, SubjectSet

**Comment by camallen** [comment]
https://github.com/zooniverse/panoptes-python-client/wiki/Delete-a-project I'm not sure that we've implemented the resource delete method yet though. The same would apply for subject set too.

I believe adding an existing workflow to a new project will copy the workflow object without data. e.g. 
``` python 
workflow = Workflow.find(1)
project = Project()
project.links.workflow = workflow
```
Try it out and feel free to create a wiki entry for this.

**Comment by astopy** [comment]
I'm going to close this now that there's documentation on Read the Docs that covers all the supported classes/methods:

http://panoptes-python-client.readthedocs.io/en/latest/

But I'll note that deleting objects isn't supported at the moment. Do feel free to open another issue as a feature request if that's needed, as well as opening new issues/PRs for anything we could add to the docs.
