### ISSUE TITLE
Is the reload after save required when creating resources?

### ISSUE THREAD

**Issue by camallen** [zooniverse/panoptes-python-client#83]
[Here](https://github.com/zooniverse/panoptes-python-client/blob/38c482da6441ae0bd3251434771a17f6f2332ba8/panoptes_client/panoptes.py#L552) the client reloads the resource after successful save. 

The API response from the 201 create action should include the full representation of the created object. We may not be including the correct ETAG in that response on this though and i think this is the reason.

If we did return the ETAG on create / update responses as well then i assume the reload after save is no longer required?

**Comment by astopy** [comment]
Yes, I think the only reason it reloads is to get the etag.

**Comment by camallen** [comment]
i'm going to add the ETAG to the create action in panoptes.
