### ISSUE TITLE
Does not work on Python 3

### ISSUE THREAD

**Issue by bamford** [zooniverse/panoptes-python-client#84]
The `unicode` built-in function [is used](https://github.com/zooniverse/panoptes-python-client/blob/master/panoptes_client/panoptes.py#L402), but it is not available in Python 3.  A possible workaround is [here](http://python-future.org/compatible_idioms.html#unicode).

**Comment by bamford** [comment]
Custom iterable classes also do not work, e.g. `ResultPaginator`.

**Comment by astopy** [comment]
@bamford If you have time, I'd really appreciate it if you could try the `python-3` branch from #87 and let me know if you find any other problems.

**Comment by bamford** [comment]
A bit late, but I have now run my notebooks in Python 3.4.5 with the latest panoptes-client master branch (88e82ae) and it all ran fine.  Thanks!

**Comment by astopy** [comment]
Great, thanks for the update!
