### ISSUE TITLE
Retrieving SubjectSet classifications

### ISSUE THREAD

**Issue by brendancol** [zooniverse/panoptes-python-client#85]
Hey hey,

Can you guys provide an example of retrieving Subject classifications by `SubjectSet`?

Thanks,

Brendan

**Comment by CKrawczyk** [comment]
You can look up classifications for a given `subject_id` (and `workflow_id` if the subject belongs to more than one workflow) using `Classification.where`, placing that in a loop over the subjects in a subject_set will give you the classifications for each subject in the subject_set.

```python
for subject in SubjectSet.find(subject_set_id).subjects():
  for classification in Classification.where(scope='project', workflow_id=workflow_id, subject_id=subject.id):
      # do something with classification
```

**Comment by brendancol** [comment]
hey @CKrawczyk thanks for the response. This works fine of one-off grabs, but will be a bit chatty for getting all data.  You know of a way to do the same thing without a separate request per subject?

**Comment by astopy** [comment]
This won't make one request per subject. The `where` method returns an iterator that yields one classification at a time, but behind the scenes the client will fetch whole pages of subjects, automatically requesting the next page when needed.

Also, since classifications don't change you can pass a `last_id` option containing the ID of the last classification you processed and the API will just return the ones which are newer than that.

**Comment by astopy** [comment]
Oh wait, I just re-read @CKrawczyk's example code. You're right that it will make one request per subject.

**Comment by CKrawczyk** [comment]
You can take the inner loop to and leave off the `subject_id` to get classifications by workflow, not sure of a way to do it by subject set in a single call, @astopy do you know if the API has a route for that?

**Comment by camallen** [comment]
@brendancol you should get the classification data at intervals (using last_id) and store it locally for your subject_set searches. I'm hesitant to offer this feature API side as it's expensive to query this table (large, write heavy).

**Comment by astopy** [comment]
One option would be to use the CSV exports and filter by subject set in there. It's not optimal, but there's no option in the API to do an export of a subject set's classifications.

I haven't tested it, but something like this should be pretty close:

```python
import csv

SUBJECT_SET_ID = '1234'

p = Project.find(...)

subjects_f = p.get_export('subjects', generate=True, wait_timeout=3600)
subjects = {
    subject['subject_id'] for subject in csv.DictReader(subjects_f) 
    if subject['subject_set_id'] == SUBJECT_SET_ID 
}

classifications_f = p.get_export('classifications', generate=True, wait_timeout=3600)
for classification in csv.DictReader(classifications_f):
    if not classification['subject_ids'] in subjects:
        continue

    ... process classification ...
```

**Comment by astopy** [comment]
Closing this for now.
