### ISSUE TITLE
Did zooniverse validation change break deleting subjectsets?

### ISSUE THREAD

**Issue by brendancol** [zooniverse/panoptes-python-client#90]
Hey Zooniverse,

I'm having trouble deleting a subject_set.  Should the following approach work:
```python
my_subjectset.delete(my_subjectset.id, headers={'If-Match': my_subjectset.etag})
```
this results in `Panoptes API exception: json controller: PreconditionalFailed` for me, but I thought this worked before.
 I was wondering if there was a recent breaking change server-side.  Maybe something like:
https://github.com/zooniverse/Panoptes/commit/4d9689f32221541ecc9c5efa013ed2dd357b3367

Is there a better way to delete subjectsets than the style above?

Thanks so much for great work.

**Comment by camallen** [comment]
what does your `my_subjectset.etag` value look like? server side should respect both weak and strong etags. 

Also seems you have to pass the etag in as a keywork param to the delete request [here](https://github.com/zooniverse/panoptes-python-client/blob/9abadd1953ccca4c472ccf8294a45f9eef550e2e/panoptes_client/panoptes.py#L276) and the client will update the header [here](https://github.com/zooniverse/panoptes-python-client/blob/9abadd1953ccca4c472ccf8294a45f9eef550e2e/panoptes_client/panoptes.py#L108)

**Comment by astopy** [comment]
@camallen The `delete_request` method you've linked to there isn't the same one being used here (`Panoptes.delete_request` vs `PanoptesObject.http_delete`)

@brendancol The example you've given should work. One thing to note is that the delete method you're using isn't intended to be used to directly delete objects -- it's actually a low-level class method for sending HTTP delete requests (and it's actually been renamed in the latest version). It works for me when I try it:

```python
>>> s = SubjectSet.find(8720)
>>> SubjectSet.http_delete(s.id, headers={'If-Match': s.etag})
(None, None)
>>> s = SubjectSet.find(8783)
>>> s.http_delete(s.id, headers={'If-Match': s.etag})
(None, None)
```

First thing to try is updating to the latest version of the client (`pip install -U panoptes-client`) and see if that helps.
