### ISSUE TITLE
Allowing retrieval of workflow supplying a specific version id

### ISSUE THREAD

**Issue by scottcoughlin2014** [zooniverse/panoptes-python-client#92]
It is possible via the API: http://docs.panoptes.apiary.io/#reference/workflows/workflow-version/retrieve-a-single-version
and would be really useful within the python client!
Thanks!
SCotty

**Comment by scottcoughlin2014** [comment]
Thanks!

**Comment by camallen** [comment]
Just be aware that looking up via the specific id will only work if you have the version resource ID not the workflow version index. This is the API bug https://github.com/zooniverse/Panoptes/issues/1039

**Comment by scottcoughlin2014** [comment]
Good to know thanks!
